CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    groups_id INTEGER
      REFERENCES groups(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    token TEXT,
    password TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);