CREATE TYPE category_type AS ENUM (
  'Living Room',
  'Dining Room',
  'Kitchen',
  'Bedroom',
  'Laundry Room',
  'Bathroom',
  'Garage',
  'Outdoor/Patio'
);

CREATE TABLE products (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER
    REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  comments TEXT,
  category category_type NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);
